--- #YAML:1.0
name:                DBIx-SimplePerl
version:             1.90
abstract:            Perlish access to DBI
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Accessor:               0.22
    DBI:                           1.5
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Joseph Landman <landman@scalableinformatics.com>
